# Generated by Django 2.0.3 on 2018-09-04 11:38

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxBasData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='值')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('type_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='类型描述')),
                ('add_who', models.IntegerField(blank=True, null=True, verbose_name='添加人')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('edit_who', models.IntegerField(blank=True, null=True, verbose_name='编辑人')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
            ],
            options={
                'db_table': 'tax_bas_data',
                'verbose_name_plural': '基础数据',
                'verbose_name': '基础数据',
            },
        ),
        migrations.CreateModel(
            name='TaxBasKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('keyword', models.CharField(max_length=50, unique=True, verbose_name='关键字')),
                ('amplification', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='全局放大倍数')),
                ('add_who', models.IntegerField(blank=True, null=True, verbose_name='添加人')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('edit_who', models.IntegerField(blank=True, null=True, verbose_name='编辑人')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
            ],
            options={
                'db_table': 'tax_bas_keyword',
                'verbose_name_plural': '关键字',
                'verbose_name': '关键字',
            },
        ),
        migrations.CreateModel(
            name='TaxBasStopWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('word', models.CharField(max_length=50, unique=True, verbose_name='停用词')),
                ('add_who', models.IntegerField(blank=True, null=True, verbose_name='添加人')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('edit_who', models.IntegerField(blank=True, null=True, verbose_name='编辑人')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
            ],
            options={
                'db_table': 'tax_bas_stopword',
                'verbose_name_plural': '停用词',
                'verbose_name': '停用词',
            },
        ),
        migrations.CreateModel(
            name='TaxBasSynonym',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('word', models.CharField(max_length=50, unique=True, verbose_name='同义词')),
                ('add_who', models.IntegerField(blank=True, null=True, verbose_name='添加人')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('edit_who', models.IntegerField(blank=True, null=True, verbose_name='编辑人')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('keyword', models.ForeignKey(db_column='keyword', on_delete=django.db.models.deletion.CASCADE, to='mgbase.TaxBasKeyword', to_field='keyword', verbose_name='关键字')),
            ],
            options={
                'db_table': 'tax_bas_synonym',
                'verbose_name_plural': '同义词',
                'verbose_name': '同义词',
            },
        ),
        migrations.CreateModel(
            name='TaxExtendQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('keyword', models.CharField(max_length=50, verbose_name='关键字')),
                ('tf_value', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='tf')),
                ('idf_value', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='idf')),
                ('weighted_value', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='权重')),
                ('amplification', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='放大倍数')),
                ('add_who', models.IntegerField(blank=True, null=True, verbose_name='添加人')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('edit_who', models.IntegerField(blank=True, null=True, verbose_name='编辑人')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
            ],
            options={
                'db_table': 'tax_extend_question',
                'verbose_name_plural': '扩展问题明细',
                'verbose_name': '扩展问题明细',
            },
        ),
        migrations.CreateModel(
            name='TaxExtendQuestionHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('desc', models.CharField(max_length=255, verbose_name='描述')),
                ('add_who', models.IntegerField(blank=True, null=True, verbose_name='添加人')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('edit_who', models.IntegerField(blank=True, null=True, verbose_name='编辑人')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
            ],
            options={
                'db_table': 'tax_extend_question_header',
                'verbose_name_plural': '扩展问题',
                'verbose_name': '扩展问题',
            },
        ),
        migrations.CreateModel(
            name='TaxExtendQuestionSynonym',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('word', models.CharField(max_length=50, verbose_name='同义词')),
                ('add_who', models.IntegerField(blank=True, null=True, verbose_name='添加人')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('edit_who', models.IntegerField(blank=True, null=True, verbose_name='编辑人')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('extend_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgbase.TaxExtendQuestion', verbose_name='扩展问题明细')),
            ],
            options={
                'db_table': 'tax_extend_question_synonym',
                'verbose_name_plural': '局部同义词',
                'verbose_name': '局部同义词',
            },
        ),
        migrations.CreateModel(
            name='TaxKnowledge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='点击数')),
                ('sd_question', models.CharField(max_length=1000, verbose_name='问题')),
                ('sd_answer', DjangoUeditor.models.UEditorField(max_length=4000, verbose_name='答案')),
                ('class_tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='分类标签')),
                ('add_who', models.IntegerField(blank=True, null=True, verbose_name='添加人')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('edit_who', models.IntegerField(blank=True, null=True, verbose_name='编辑人')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
            ],
            options={
                'db_table': 'tax_knowledge',
                'verbose_name_plural': '知识',
                'verbose_name': '知识',
            },
        ),
        migrations.CreateModel(
            name='TaxQuestionSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('session_key', models.CharField(max_length=50, unique=True, verbose_name='标识符')),
                ('source', models.CharField(max_length=10, verbose_name='来源')),
                ('status', models.CharField(max_length=1, verbose_name='状态')),
                ('add_who', models.IntegerField(blank=True, null=True, verbose_name='添加人')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('edit_who', models.IntegerField(blank=True, null=True, verbose_name='编辑人')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
            ],
            options={
                'db_table': 'tax_question_session',
                'verbose_name_plural': '人工审核',
                'verbose_name': '问答会话',
            },
        ),
        migrations.CreateModel(
            name='TaxSolveUnSolve',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('question', models.CharField(max_length=1000, verbose_name='问题')),
                ('solve', models.PositiveIntegerField(default=0, verbose_name='解决/未解决')),
                ('is_knowledge', models.BooleanField(default=False, verbose_name='是否知识')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='答案(小穗)')),
                ('add_who', models.IntegerField(blank=True, null=True, verbose_name='添加人')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('edit_who', models.IntegerField(blank=True, null=True, verbose_name='编辑人')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('session_key', models.ForeignKey(db_column='session_key', on_delete=django.db.models.deletion.CASCADE, to='mgbase.TaxQuestionSession', to_field='session_key', verbose_name='标识符')),
            ],
            options={
                'db_table': 'tax_solve_unsolve',
                'verbose_name_plural': '会话明细',
                'verbose_name': '会话明细',
            },
        ),
        migrations.CreateModel(
            name='TaxUnSolveMail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('content', models.TextField(blank=True, null=True, verbose_name='邮件内容')),
                ('desc', models.CharField(max_length=1000, verbose_name='描述')),
                ('add_who', models.IntegerField(blank=True, null=True, verbose_name='添加人')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('edit_who', models.IntegerField(blank=True, null=True, verbose_name='编辑人')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('session_key', models.ForeignKey(db_column='session_key', on_delete=django.db.models.deletion.CASCADE, to='mgbase.TaxQuestionSession', to_field='session_key', verbose_name='标识符')),
            ],
            options={
                'db_table': 'tax_unsolve_mail',
                'verbose_name_plural': '未解决邮件',
                'verbose_name': '未解决邮件',
            },
        ),
        migrations.AddField(
            model_name='taxextendquestionheader',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extend_question', to='mgbase.TaxKnowledge', verbose_name='知识'),
        ),
        migrations.AddField(
            model_name='taxextendquestion',
            name='extend_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgbase.TaxExtendQuestionHeader', verbose_name='扩展问题'),
        ),
        migrations.CreateModel(
            name='TaxKnowledgeProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'verbose_name_plural': '专家调整',
                'verbose_name': '专家调整',
            },
            bases=('mgbase.taxknowledge',),
        ),
    ]
